### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Hedin4eg** [mfr966/otcs-webreport#1]
![image](https://user-images.githubusercontent.com/12122698/234551977-aace39f5-2089-4b9e-8aa1-3e47700bead5.png)
why does it show everything as a comment after some line? happens to most of my WRs..

**Comment by mfr966** [comment]
Thanks for the feedback. This is indeed a missing condition (LL_REPTAG=), which is screwing everything up... I'll try to fix that asap and to make recovery more robust.

**Comment by mfr966** [comment]
Should be resolved with version 0.1.0.
